### ISSUE TITLE
Review Needed

### ISSUE THREAD

**Issue by chamboug** [PolytechLyon/isi3-tp1-graph-bect-chambouvet#1]

**Comment by Slashgear** [comment]
- 👍 Le rapport est très bien. Rappeler vous l'UML de classe est un super outil de représentation. ça me permet de vérifier que vous avez bien compris.

- [ ] Si je veux vraiment vous embêter les nommages de certaines variables ne respectent pas les convention qu'on a pu déterminer ensemble.

- [ ] A quoi sert la méthode `hashcode` que vous avez implémenté dans `Node` ? 

- [ ] Vu que votre code est pas trop mal, petite question en plus 😄 Dans les fait ça sert à quoi les StringBuilder par rapport à une concaténation en Java classique ?

**Comment by corentin521** [comment]
Bonjour,

Merci pour ce retour rapide ! 

Nous venons de renommer plusieurs variables dont le nom n'étant pas très parlant. 

Concernant la méthode `hashCode()` de `Node`, nous l'avons redéfinie car la liste des nœuds déjà visités (`visitedNodes`) se présente sous la forme d'une `LinkedHashSet<Node>`. Par conséquent, la méthode `hashCode()` est appelée lors de l'insertion afin de vérifier si le nœud, et plus particulièrement son hash n'est pas déjà présent dans la liste `visitedNodes`.

Quant à la question supplémentaire, la concaténation via l'opérateur `+` est moins performante qu'une concaténation effectuée par le biais d'un objet StringBuilder. En effet, prenons l'exemple suivant : 

```
String moitieDePhrase1 = "J'espère que mes souvenirs";
String moitieDePhrase2 = " du cours sont intacts.";
String resultat = moitieDePhrase1 + moitieDePhrase2;
```
Lors de la troisième instruction, un objet StringBuilder est ajouté auquel sera ajouté moitieDePhrase1 et moitieDePhrase2. Ensuite le tout sera converti en String. 

Lors de la phase de compilation, l'instruction sera transformée en : 

`String resultat = new StringBuilder().append(moitieDePhrase1).append(moitieDePhrase2).toString(); `

Chaque concaténation via l'opérateur `+` entraîne donc la création d'un objet StringBuilder qui sera supprimé par le ramasse-miettes plus tard. Imaginons qu'une telle concaténation soit placée dans une boucle qui itère 1000 fois, 1000 objets StringBuilder seront créés et laissés à l'abandon après avoir fait appel à la méthode `toString()`. Cette concaténation est donc plus coûteuse que celle effectuée via un objet StringBuilder.
